default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_new_rails_app_development
  username: postgres
  password: Duque

test:
  <<: *default
  database: my_new_rails_app_test
  username: postgres
  password: Duque

production:
  <<: *default
  database: my_new_rails_app_production
  username: my_new_rails_app
  password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>